version: "3"
services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    image: client
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - server
    environment:
      - SERVER_ADDR=server:9001
      - HASHCASH_BITS=20
      - HASHCASH_SALT_LENGTH=10
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    image: server
    expose:
      - 9001
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - HASHCASH_BITS=20
      - HASHCASH_SALT_LENGTH=10
